### ISSUE TITLE
postgres dataType convert wrong 

### ISSUE THREAD

**Issue by KingDracula** [spinlud/sequelize-typescript-generator#26]
i was used this to generator model with postgres,but the column dataType was convert wrong ,
how to fix it
![image](https://user-images.githubusercontent.com/13584613/130940862-bb5ea7cb-1e3e-448b-910b-a36045949b78.png)
![image](https://user-images.githubusercontent.com/13584613/130940922-7abb43da-4237-474e-a8c1-2bd63957a8d6.png)
![image](https://user-images.githubusercontent.com/13584613/130940994-ee5ac9c0-8d86-4600-8a4b-7bb50af78ef7.png)

**Comment by spinlud** [comment]
Hi, if you are talking about the `bigint` column mapped to `string` in javascript, that's because the Postgres driver works that way. To avoid precision errors, types like `bigint`, `decimal` and `numeric` are mapped to javascript string by the driver. You should explicitly cast it to a number in javascript if you need to.
